spring:
  application:
    name: rainfall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b224d071ef02936a6012285e990306ff
            client-secret: DzB9uvE3eO7SXLKpo0NyR58lJcU40vRe
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: 3600000  # 토큰 만료 시간 (밀리초)


springdoc: # Swagger ??
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8080