version: '3.8'

services:
  app:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rainfall
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 20375570
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
#    links:
#      - db
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
#    networks:
#      - mynet

  db:
    hostname: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 20375570
      MYSQL_DATABASE: rainfall
    ports:
      - "3306:3306"
#    networks:
#      - mynet

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

#networks:
#  mynet:
#    driver: bridge